server:
  port: 80
spring:
  datasource:
     type: com.alibaba.druid.pool.DruidDataSource
#     type: UNPOOLED
     driverClassName: oracle.jdbc.driver.OracleDriver
     url: jdbc:oracle:thin:@//47.96.254.186:1521/orcl
     username: oss
     password: oss
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
logging:
  level:
    root: info
    org.mybatis: info
    com.bootdo: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    proxy-target-class: true